GET http://localhost:3000/api/auth

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Koji Adriano Jr",
    "email": "iisparkplugiiog@gmail.com",
    "username": "username00",
    "password": "pass123",
    "confirm_password": "pa"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "kojiadriano98",
    "password": "pass123"
}

###
PATCH http://localhost:3000/api/auth/manage_otp/5f4e23ef9ef66301f4269d8d

###
POST http://localhost:3000/api/auth/validate_otp/5f51d369334fce0153665b1c
Content-Type: application/json

{
    "otp_token": "598856"
}

###
GET http://localhost:3000/api/auth/generate_otp/5f51d369334fce0153665b1c
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTkyMDM4MTcsInVzZXJuYW1lIjoia29qaWFkcmlhbm85OCIsInBhc3N3b3JkIjoicGFzczEyMyIsImlhdCI6MTU5OTIwMDIxN30.tCYTMAaY_yi0oHcp9RNRjFpUmDxvwwXN13y6DaQrb5o